src/Tanka.Web/Controllers/BlogController.cs
namespace Tanka.Web.Controllers
{
    using System;
    using Infrastructure;
    using Models;
    using Raven.Client;
    using Microsoft.AspNetCore.Mvc;

    [Route("")]
    public class BlogController : Controller
    {
        private readonly IMarkdownRenderer _markdownRenderer;
        private readonly IDocumentStore _documentStore;

        public BlogController(IDocumentStore documentStore, IMarkdownRenderer markdownRenderer)
        {
            _markdownRenderer = markdownRenderer;
            _documentStore = documentStore;
        }

        [HttpGet("", Order=1000)]
        public ActionResult Home(int skip = 0, int take = 100)
        {
            var model = new HomeModel();

            using (IDocumentSession session = _documentStore.OpenSession())
            {
                var site = session.GetSiteSettings();

                // todo: refactor into attribute
                if (site == null)
                    return RedirectToAction("Offline", "Errors");

                var total = 0;
                var posts = session.GetPublishedBlogPosts(skip, take, out total, _markdownRenderer);
                
                ViewBag.Title = site.Title;
                ViewBag.SubTitle = site.SubTitle;

                model.Posts = posts;
                model.TotalResults = total;

            }

            return View(model);
        }

        [HttpGet("{year:int}/{month:int}/{day:int}/{slug}")]
        public ActionResult BlogPost(int year, int month, int day, string slug)
        {
            using (IDocumentSession session = _documentStore.OpenSession())
            {
                var post = session.GetPublishedBlogPost(slug, _markdownRenderer);

                if (post == null)
                    return NotFound();

                var site = session.GetSiteSettings();
                ViewBag.Title = site.Title;
                ViewBag.SubTitle = post.Title;
                return View(new BlogPostModel
                {
                    Post = post
                });
            }
        }

        [Obsolete("Will be removed in v1.2")]
        [HttpGet("{slug}")]
        public ActionResult BlogPostObsolete(string slug)
        {
            if (slug.StartsWith("_admin"))
            {
                return RedirectToActionPermanent("Home", "Admin");
            }

            using (IDocumentSession session = _documentStore.OpenSession())
            {
                var post = session.GetPublishedBlogPost(slug, _markdownRenderer);

                if (post == null)
                    return NotFound();

                return RedirectToActionPermanent("BlogPost", new
                {
                    year= post.PublishedOn.Value.Year,
                    month = post.PublishedOn.Value.Month,
                    day = post.PublishedOn.Value.Day,
                    slug
                });
            }
        }
    }
}

src/Tanka.Web/Controllers/TagsController.cs
namespace Tanka.Web.Controllers
{
    using System;
    using Infrastructure;
    using Models;
    using Raven.Client;
    using Microsoft.AspNetCore.Mvc;

    [Route("tags")]
    public class TagsController : Controller
    {
        private readonly IMarkdownRenderer _markdownRenderer;
        private readonly Func<IDocumentSession> _sessionFactory;

        public TagsController(IDocumentStore sessionFactory, IMarkdownRenderer markdownRenderer)
        {
            _markdownRenderer = markdownRenderer;
            _sessionFactory = sessionFactory.OpenSession;
            //this.RequiresInstallerDisabled(sessionFactory);
        }

        [Route("{tag}")]
        public ActionResult Tag(string tag, int skip = 0, int take = 100)
        {
            using (IDocumentSession session = _sessionFactory())
            {
                int total;
                var posts = session.GetPublishedBlogPosts(tag, skip, take, out total, _markdownRenderer);
                var site = session.GetSiteSettings();
                ViewBag.SubTitle = tag;
                ViewBag.Title = site.Title;

                return View(new HomeModel {Posts = posts, TotalResults = total});
            }
        }
    }
}

src/Tanka.Web/ViewComponents/HistoryViewComponent.cs
namespace Tanka.Web.ViewComponents
{
    using System.Threading.Tasks;
    using Core;
    using Documents.Indexes;
    using Infrastructure;
    using Microsoft.AspNet.Mvc;
    using Raven.Client;

    public class HistoryViewComponent : ViewComponent
    {
        private readonly IDocumentStore _documentStore;
        private readonly IMarkdownRenderer _markdownRenderer;

        public HistoryViewComponent(IDocumentStore documentStore, IMarkdownRenderer markdownRenderer)
        {
            _documentStore = documentStore;
            _markdownRenderer = markdownRenderer;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var blogPosts = new PublishedBlogPosts(_documentStore, _markdownRenderer);
            var history = await blogPosts.GetMonthlyHistoryAsync().ConfigureAwait(false);

            return View(history);
        }
    }
}

src/Tanka.Web/ViewComponents/TagCloudViewComponent.cs
namespace Tanka.Web.ViewComponents
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Core;
    using Microsoft.AspNet.Mvc;
    using Raven.Client;

    public class TagCloudViewComponent : ViewComponent
    {
        private readonly PublishedBlogPostTags _tagCloud;

        public TagCloudViewComponent(IDocumentStore documentStore)
        {
            _tagCloud = new PublishedBlogPostTags(documentStore);
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var tags = await _tagCloud.GetTagCounts().ConfigureAwait(false);
            tags = tags.Select(tag => new KeyValuePair<string, int>(tag.Key, Normalize(tag.Value)))
                .OrderByDescending(t => t.Value);

            return View(tags);
        }

        private int Normalize(int value)
        {
            if (value < 6)
                return value;

            return 6;
        }
    }
}

src/Tanka.Web/Views/Tags/Tag.cshtml
@model HomeModel
@{
    ViewBag.PageTitle = ViewBag.SubTitle + " | " + ViewBag.Title;
}
<div class="row">
    <div class="articles">
        @if (Model.Posts != null)
        {
            foreach (var post in Model.Posts)
            {
                <text>
                    <div class="article">
                        <article>
                            <hroup>
                                <h1 class="page-header">
                                    @Html.ActionLink(post.Title, "BlogPost", "Blog",
                                        new {year = post.PublishedOn.Value.Year, month = post.PublishedOn.Value.Month, day = post.PublishedOn.Value.Day, slug = post.Slug})
                                </h1>
                                <h3 class="meta">
                                    <small> Written by @post.Author on @post.PublishedOn.Value.ToString("d")</small>
                                    <small>
                                        @Html.ActionLink("", "BlogPost", "Blog", null, null, "disqus_thread",
                                            new
                                            {
                                                year = post.PublishedOn.Value.Year,
                                                month = post.PublishedOn.Value.Month,
                                                day = post.PublishedOn.Value.Day,
                                                slug = post.Slug
                                            },
                                            new
                                            {
                                                data_disqus_identifier = @post.Id,
                                                @class = "badge"
                                            })</small>
                                </h3>
                            </hroup>
                            <div class="tags">
                                @foreach (var tag in post.Tags)
                                {
                                    @: <span><a href="/tags/@tag">@tag.ToUpperInvariant()</a></span>
                                }
                            </div>
                            <div class="content">
                                @Html.Raw(post.Content)
                            </div>
                        </article>
                    </div>
                </text>
            }
        }
    </div>
    <div class="right-side">
        @await Component.InvokeAsync("History")
        @await Component.InvokeAsync("TagCloud")
    </div>
</div>
@section footer {
    @Disqus.Render(null)
}